import { Instrument_Sans } from "next/font/google";
import "@fortawesome/free-solid-svg-icons";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import "./globals.css";

const font = Instrument_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "PixelPilot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={font.className}>
      <body>{children}</body>
    </html>
  );
}
